### ISSUE TITLE
Server Crashes when trying to load Reagenchant

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [LogicTechCorp/Reagenchant#10]
Reagenchant version: 3.0.1
Forge Version: 36.2.8
Minecraft Version: 1.16.5
Crash report: https://gist.github.com/NJL5390/6cf9549815eeead62837ae29af0f8ead

Hi,
After attempting to test this mod on my modded server, I have found that the server just crashes when attempting to load the mod. This doesn't happen in singleplayer and only happens on a server.

**Comment by tweakbsd** [comment]
Theres Client Side Code that is tried to be run on the server.

**Comment by LogicTechCorp** [comment]
This crash has been fixed in the latest version.
