### ISSUE TITLE
[REQUEST] Optionally separate Ubreaking III change

### ISSUE THREAD

**Issue by supersaiyansubtlety** [LogicTechCorp/Reagenchant#5]
It would be nice to be able to separate the behavior that's added to unbreaking to a separate enchantment. 
Also, thanks for this mod! It's a great idea and I appreciate that it's customizable.

**Comment by LogicTechCorp** [comment]
The unbreaking tweak has been removed in the latest version. It may take some time for CurseForge to approve it.
