### ISSUE TITLE
[1.12.2] New Reagent Items Added via Jsons do not show in JEI tab

### ISSUE THREAD

**Issue by TeetoKaziim** [LogicTechCorp/Reagenchant#6]
My Custom Reagents are working perfectly, except for one detail:

![image](https://user-images.githubusercontent.com/25490944/78616117-f6a91800-7838-11ea-8561-2f9d0c3d5b66.png)

```
{
	"item": "quark:black_ash",
	"enchantments": [
		{
			"minimumEnchantmentLevel": 1,
			"enchantment": "enderzoo:witherweapon",
			"probability": 1.0,
			"maximumEnchantmentLevel": 1,
			"reagentCost": 1
		}
	]
}
```

Despite working as a valid enchanting reagent, only the default list of reagent items show up in the JEI tab for the mod.

**Comment by LogicTechCorp** [comment]
Closing this per the reasons discussed in the discord.
