### ISSUE TITLE
[1.15.2] Mod not working + Crash on mod config ([...] Root resources can only be filenames [...])

### ISSUE THREAD

**Issue by rafaelhr** [LogicTechCorp/Reagenchant#8]
I installed Reagenchant 2.0.0 and LibraryEx 3.0.0, but didn't see any config files being generated, nor the mod was at all working. When I went into the Mods section on Minecraft's main menu and clicked Reagenchant, the game crashed.

I have reproduced this error on a .minecraft with only forge, Reagenchant and LibraryEx installed, so it's probably not a cross-mod incompatibility issue.

Crash log [here](https://pastebin.com/HLt4Lcv0).

Thanks in advance.

**Comment by LogicTechCorp** [comment]
There are no config files for 1.14+ since data packs are now used. The ```/reagenchant reagent``` command will allow you to create and customize reagents. The customized reagents are saved in a data pack in the worlds ```datapacks``` folder. The crash when clicking on the mod info has been fixed in the latest version.
